### ISSUE TITLE
[Bug] Scrolling stops working after using color select tool

### ISSUE THREAD

**Issue by Sanokei** [Ragzouken/domino2#2]
Zooming in and out does not work after using the color select tool. Everytime you use it you have to switch tabs and switch back for the funtionality to come back again.

This is happening for my Windows computer for Chrome Version 91.0.4472.124 with JS version V8 9.1.269.36

**Comment by Ragzouken** [comment]
I'm unable to replicate this for Chrome Version 92.0.4515.107 on Windows (though I don't think it's ever been broken like that for me on previous versions). You're talking about the card/board background color selects? Are you using with mouse wheel, laptop trackpad, or something else? For me it seems to work as normal however much I click around the color select. Only thing I do notice is that the browser's eye-dropper prevents zooming but I'm not sure it's within my power to change that (and cancelling out restores zoom, so I don't think it's the problem you're describing)

**Comment by Sanokei** [comment]
I am using a standard mouse, with the scroll wheel.

I actually meant the eye dropper as you call it as well, however for me, "cancelling out" doesn't restore zoom. I select a color i want to copy and then it prevents me from zooming in and out on a mouse. Its honestly only a small inconvenience, and im pretty sure its unfixable, unless the actual plugin is fixed itself.

Thanks though
